### PR TITLE
ngMdIconServiceProvider

### PR DESCRIPTION
**Pull request by sscovil**
This pull request enables developers to register new icons as follows:

```javascript
angular.module('myApp', ['ngMaterial', 'ngMdIcons'])
    .config(ngMdIconsConfig);

function ngMdIconsConfig() {
    ngMdIconServiceProvider.addShape('my-custom-icon', '<path d="..." />');
}
```

The `ngMdIconServiceProvider.addShape` method is chainable, so you can add multiple shapes like this:

```javascript
ngMdIconServiceProvider
    .addShape('custom-icon-a', '<path d="..." />')
    .addShape('custom-icon-b', '<path d="..." />')
    .addShape('custom-icon-c', '<path d="..." />')
;
```

Alternatively, you can use the `ngMdIconServiceProvider.addShapes` (plural) method that accepts an object as a parameter:

```javascript
ngMdIconServiceProvider.addShapes({
    'custom-icon-a': '<path d="..." />',
    'custom-icon-b': '<path d="..." />',
    'custom-icon-c': '<path d="..." />'
});
```

Finally, you can access the `shapes` object used by the `ngMdIcon` directive from a controller or another service by calling `ngMdIconService.getShapes()` or `ngMdIconService.getShape('shape-name')`.

This PR implements the changes suggested in the discussion on #28.

### CODE REVIEW

**Comment by sscovil** [comment]
@urmilparikh Yeah, I forgot to mention the configurable viewBox attribute in my pull request. Sorry about that. It is only necessary when using custom SVG data that is defined for larger a viewBox.

For example, this Font Awesome beer icon needs a viewBox setting of `0 0 1792 1792`:

```html
<path d="M704 896v-384h-256v256q0 53 37.5 90.5t90.5 37.5h128zm1024 448v192h-1152v-192l128-192h-128q-159 0-271.5-112.5t-112.5-271.5v-320l-64-64 32-128h480l32-128h960l32 192-64 32v800z"/>
```

There is another caveat worth mentioning, regarding the viewBox setting. It may be confusing, because the viewBox attribute is normally camelCase...but because AngularJS "normalizes" and "denormalizes" attribute names, you need to set it using kebab-case.

Example:

```html
<ng-md-icon icon="fa-beer" view-box="0 0 1792 1792"></ng-md-icon>
```

**Comment by urmilparikh** [comment]
Hi @sscovil, I updated demo page with few examples (for #34), but I couldn't get `ngMdIconService.getShape` working.

Request you to update `demo.js` for `custom-delete` icon.

**Comment by sscovil** [comment]
@urmilparikh I'm not able to reproduce the problem. Here is a [JSFiddle](http://jsfiddle.net/sscovil/uvbn9ws8/) with your code from `demo.js` and the current code from `angular-material-icons.js` on `master`.

Can you provide an example that reproduces the problem you are having?

**Comment by urmilparikh** [comment]
Thanks, @sscovil.
I wasn't able to access ngMdIconService.
Later I changed code to use ngMdIconServiceProvider itself for getting shapes and that is working.

**Comment by sscovil** [comment]
@urmilparikh I see. That's an easy mistake to make.

Also, I notice you renamed the `provider` variable to `service` in 576768adb4ef898f6739c2b3c26e85c617ec9977 ... which is not really accurate. The function returns a Provider object. The `$get` method of the provider is the factory that produces the service. Not a big deal, but I thought it was worth mentioning.

**Comment by urmilparikh** [comment]
I should change that to provider.
How do I return service and access it from outside?

**Comment by sscovil** [comment]
Actually, a Provider is supposed to be a constructor...so I was writing it incorrectly, in that sense. According to AngularJS, you should replace the `provider` variable name with `this`...and you should not need to return anything.

During the run phase, Angular calls the `$get` method of a provider to get the service. At the very bottom of `angular-material-icons.js`, you'll see the factory method that is returned by `$get`. I have a habit (read: OCD) of putting functions in alphabetical order.

Check out [the $provide docs](https://docs.angularjs.org/api/auto/service/$provide) if you're interested in the subject. Also, [this article](http://anandmanisankar.com/posts/angularjs-provider-subsystem/) explains quite a bit.

**Pull request merged**
