### PR TITLE
Add some icons

### PR DESCRIPTION
**Pull request by tigranbalayan**
- vk social
  - programming languages
  - programming libraries
  - tools
  - os
...

### CODE REVIEW

**Comment by urmilparikh** [comment]
May I know the source of these icons?

**Comment by tigranbalayan** [comment]
Yeah,
Some of them I did myself and some from researching result

**Comment by tigranbalayan** [comment]
I have used all of this icons for my visit card website, but it is not online yet.

**Comment by dresslerit** [comment]
Can you provide us the license and copyright information (also source) of those icons you didn't created?
We need them because we won't to publish illegal "copied" icons.
And with which license do you want to publish your icons? (LGPL, MIT, ...)?

**Comment by tigranbalayan** [comment]
I used icons under MIT license.
Also I generated some of them by online generator(don't remember which of them) using png/jpg images.
I want to publish under MIT license.

**Pull request closed without merging**
