### PR TITLE
Allow for custom svg icons

### PR DESCRIPTION
**Pull request by smithgt**
Exposing ShapeService.shapes to allow for custom svg icons.

Can be used to simplify:
#16 #18

### CODE REVIEW

**Comment by sscovil** [comment]
@smithgt this looks really good. I'm looking for a similar feature, so thank you for submitting this pull request!

What might make it even better is if, instead of using `factory` to create the service, you use `provider` so custom icons could be added during the `config` phase. I'd be happy to submit a modified version of your pull request if that would be helpful.

Is this feature slated for a release yet?

**Comment by urmilparikh** [comment]
@smithgt, @sscovil, please discuss and update the pull request, I'll pull it in next release.

**Comment by smithgt** [comment]
@sscovil great suggestion.  ```provider``` sounds good to me.  go for it.

**Comment by urmilparikh** [comment]
Added this functionality as part of #30.

**Pull request closed without merging**
