### PR TITLE
Updated Google Material Icons Library to version 2.2.0

### PR DESCRIPTION
**Pull request by dresslerit**
I added 41 Icons to the plugin.
Maybe for further updates, you can add me to the collaborators. 
Greetings  Noah

### CODE REVIEW

**Comment by urmilparikh** [comment]
Can you confirm the source to be Google Material Icons repository?
Also, please update index.html for added icons.

**Comment by urmilparikh** [comment]
Added you as a collaborator.

**Comment by dresslerit** [comment]
The Icons are from the Website https://design.google.com/icons/ . I added all "new" labeled icons. I'll change the index.html and push it then to the master-branch without creating a new pull request. Or should I create for only the index.html a new one?
Greetings Noah.

**Comment by urmilparikh** [comment]
Please feel free to push it. Also note that I;m in process of fixing some issues, please check for any conflicts.

**Comment by urmilparikh** [comment]
Few notes...

1: Before adding new icons, I open .svg file in Inkscape, do `Edit -> Select All`, `Path -> Break Apart` and then selectively do `Path -> Combine` for any holes. This results in better morphing with SVGMorpheous.

2: After saving .svg file from Inkscape, I run it through svgo (https://github.com/svg/svgo) for optimized output.

Also, do not worry about generating .min.js, it is done by a script when making release.

**Comment by dresslerit** [comment]
Thank you for that tipp. I will check and minimize the path of those added icons if its not to much work.
Maybe we can make a new release after adding the index.html. We have lots of changes since version 0.6.
Remember to update bower and npm either.

**Comment by Hakier** [comment]
:+1: for new release ;)

**Pull request merged**
